import Image from "next/image";

const tel = "tel:+31648659279";
const whatsapp = "https://wa.me/31648659279?text=Hallo%20Autosleutel%20Rivierenland%2C%20ik%20heb%20hulp%20nodig%20met%20mijn%20autosleutel.";
const googleReviews = "https://www.google.com/search?q=autosleutel+rivierenland";

const services = [
  ["01", "Autosleutel bijmaken", "Een extra autosleutel laten maken? Wij zorgen voor een passende sleutel die bij uw voertuig past.", "/diensten/autosleutel-bijmaken"],
  ["02", "Autosleutels kwijt", "Geen werkende sleutel meer? Wij beoordelen de mogelijkheden voor uw voertuig en helpen u weer op weg.", "/diensten/autosleutel-kwijt"],
  ["03", "Schadevrij openen", "Buitengesloten? Wij openen uw auto zo zorgvuldig mogelijk en proberen onnodige schade te voorkomen.", "/diensten/schadevrij-openen"],
  ["04", "Mercedes contactsloten vervangen", "Problemen met het contactslot van uw Mercedes? Wij onderzoeken de klacht en vervangen geschikte contactsloten.", "/mercedes-contactslot"],
];
const coreAreas = ["Tiel", "Culemborg", "Geldermalsen", "Buren", "Zaltbommel", "Leerdam", "Gorinchem"];
const expansionAreas = ["Nijmegen", "Arnhem", "Den Bosch", "Utrecht"];
const structuredData = {"@context":"https://schema.org","@type":"Locksmith",name:"Autosleutel Rivierenland",url:"https://autosleutelrivierenland.nl",telephone:"+31648659279",email:"autosleutel.rivierenland@gmail.com",address:{"@type":"PostalAddress",addressLocality:"Tiel",addressRegion:"Gelderland",addressCountry:"NL"},areaServed:[...coreAreas,...expansionAreas].map(name=>({"@type":"City",name})),openingHoursSpecification:[{"@type":"OpeningHoursSpecification",dayOfWeek:["Monday","Tuesday","Wednesday","Thursday","Saturday","Sunday"],opens:"09:00",closes:"21:00"}]};
function PhoneIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.6 2.8 9.4 2l2.1 5.1-2.4 1.8c1.2 2.5 3.1 4.5 5.7 5.7l1.8-2.4 5.1 2.1-.8 2.8c-.4 1.5-1.8 2.5-3.4 2.4C10.2 18.8 5.2 13.8 4.5 7.7c-.2-1.6.7-3.1 2.1-3.7Z" fill="currentColor"/></svg>}
function WhatsAppIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2.5a9.4 9.4 0 0 0-8.1 14.2L2.7 21.4l4.9-1.2A9.4 9.4 0 1 0 12 2.5Zm0 16.9a7.5 7.5 0 0 1-3.8-1l-.3-.2-2.9.7.8-2.8-.2-.3a7.5 7.5 0 1 1 6.4 3.6Zm4.1-5.6c-.2-.1-1.4-.7-1.6-.8-.2-.1-.4-.1-.5.1-.2.2-.6.8-.7 1-.1.2-.3.2-.5.1-1.5-.8-2.5-1.5-3.5-3.1-.3-.5.3-.5.8-1.5.1-.2 0-.4 0-.5l-.7-1.6c-.2-.4-.4-.4-.5-.4h-.4c-.2 0-.5.1-.7.3-.2.2-.9.9-.9 2.2s.9 2.6 1 2.8c.1.2 1.8 2.9 4.4 4 .6.3 1.1.4 1.5.5.6.2 1.2.1 1.7.1.5-.1 1.4-.6 1.6-1.2.2-.6.2-1.1.1-1.2-.1 0-.3-.1-.6-.2Z" fill="currentColor"/></svg>}
function Header(){return <header className="header"><div className="container nav-inner"><a className="logo-frame" href="#top" aria-label="Autosleutel Rivierenland home"><Image src="/logo.svg" alt="Autosleutel Rivierenland" width={220} height={89} priority unoptimized/></a><nav aria-label="Hoofdnavigatie"><a className="active" href="#top">Home</a><a href="#diensten">Diensten</a><a href="/mercedes-contactslot">Mercedes contactslot vervangen</a><a href="#zakelijk">Zakelijk</a><a href="#contact">Contact</a></nav><a className="nav-phone" href={tel}><b>☎</b><span>06 48 65 92 79</span></a></div></header>}
export default function Home(){return <main id="top"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData)}}/><Header/>
<section className="hero"><div className="container hero-inner"><div className="hero-copy"><div className="eyebrow">AUTOSLEUTELSERVICE UIT TIEL</div><h1>Probleem met uw<br/><span>autosleutel?</span></h1><p className="hero-text">Autosleutel bijmaken, vervangen, een behuizing vervangen, uw auto schadevrij openen of een storing laten onderzoeken. Snel, vakkundig en op locatie in Tiel en de regio.</p><div className="actions"><a className="btn primary" href={tel}><span className="btn-icon"><PhoneIcon/></span><span>Bel direct</span><b>06 48 65 92 79</b></a><a className="btn hero-secondary" href={whatsapp} target="_blank" rel="noreferrer"><span className="btn-icon whatsapp-icon"><WhatsAppIcon/></span><span>WhatsApp</span><b>Stuur een bericht →</b></a></div><div className="hero-trust"><span>✓ Service op locatie</span><span>✓ 1 jaar garantie</span><span>✓ Geen voorrijkosten binnen Tiel</span></div></div><div className="hero-image-wrap" aria-label="Premium autosleutel op lichte beige achtergrond"/></div></section>
<section id="diensten" className="section services"><div className="container"><div className="section-head"><div><h2>Onze <em>diensten.</em></h2></div></div><div className="service-grid">{services.map(([n,title,text,href],index)=><a href={href} className={`service service-${index+1}`} key={n}><span className="service-no">{n}</span><h3>{title}</h3><p>{text}</p><b className="service-arrow">→</b></a>)}</div>
<div className="why-section"><div className="why-logo-card"><Image src="/logo.svg" alt="Autosleutel Rivierenland" width={440} height={194} unoptimized/></div><div className="why-copy-card"><label>WAAROM KIEZEN VOOR</label><h2>Autosleutel <em>Rivierenland?</em></h2><p>Bij ons bent u verzekerd van snelle, betrouwbare en professionele service. Wij staan voor kwaliteit, eerlijkheid en klanttevredenheid.</p><div className="why-points"><div><span>€</span><strong>Scherpe prijzen</strong><small>Eerlijke tarieven, geen verrassingen.</small></div><div><span>◷</span><strong>Snel geholpen</strong><small>Vaak nog dezelfde dag.</small></div><div><span>⌖</span><strong>Service op locatie</strong><small>Wij komen naar u toe, in heel de regio.</small></div><div><span>♥</span><strong>Servicegericht</strong><small>Uw tevredenheid staat voorop.</small></div><div><span>✓</span><strong>Professioneel</strong><small>Vakkundige aanpak en moderne apparatuur.</small></div><div><span>★</span><strong>Betrouwbaar</strong><small>Duidelijke communicatie.</small></div></div></div></div></div></section>
<section className="tiel-home-section"><div className="container tiel-home-grid"><div className="tiel-home-copy"><label>AUTOSLEUTELSERVICE VANUIT TIEL</label><h2>Tiel als <em>basis.</em></h2><p>Autosleutel Rivierenland is gevestigd in Tiel en helpt klanten met autosleutels in de ruime regio. Wij maken autosleutels bij, helpen wanneer u uw autosleutel kwijt bent en openen auto's schadevrij wanneer u bent buitengesloten.</p><p>Vanuit Tiel zijn wij actief in onder andere Culemborg, Geldermalsen, Buren, Zaltbommel, Leerdam en Gorinchem. Dankzij onze mobiele werkwijze kunnen wij veel werkzaamheden direct op locatie uitvoeren.</p><a className="text-link" href="/tiel">Meer over autosleutelservice in Tiel →</a></div><a className="rivierenland-map" href="/tiel" aria-label="Bekijk autosleutelservice vanuit Tiel"><div className="map-outline"><i className="map-road road-1"></i><i className="map-road road-2"></i><i className="map-road road-3"></i><span className="map-city city-tiel"><b></b>Tiel</span><span className="map-city city-culemborg"><b></b>Culemborg</span><span className="map-city city-geldermalsen"><b></b>Geldermalsen</span><span className="map-city city-buren"><b></b>Buren</span><span className="map-city city-zaltbommel"><b></b>Zaltbommel</span><span className="map-city city-leerdam"><b></b>Leerdam</span><span className="map-city city-gorinchem"><b></b>Gorinchem</span></div><div className="map-caption"><span>RIVIERENLAND</span><strong>Tiel als uitvalsbasis</strong><small>Mobiele autosleutelservice in de regio</small></div></a></div></section>
<section className="section capability"><div className="container capability-grid"><div><label>MERKEN &amp; MOGELIJKHEDEN</label><h2>Voor veel <em>gangbare automerken.</em></h2></div><div><p>De mogelijkheden verschillen per merk, model, bouwjaar en uitvoering. Daarom beoordelen wij vooraf wat er voor uw auto mogelijk is.</p><p className="excluded"><strong>Niet beschikbaar:</strong> BMW, Renault en Volvo.</p><p>Twijfelt u? Stuur ons het merk, model, bouwjaar en eventueel het kenteken.</p></div></div></section>
<section id="zakelijk" className="business"><div className="container business-box"><div><label>VOOR BEDRIJVEN</label><h2>Een praktische partner voor <em>uw werkplaats.</em></h2><p>Garages en autobedrijven kunnen bij ons terecht voor autosleutels, behuizingen, contactsloten en schadevrij openen. Zakelijke werkzaamheden kunnen op factuur worden afgehandeld.</p></div><a className="btn primary" href={whatsapp} target="_blank" rel="noreferrer">Bespreek uw aanvraag →</a></div></section>
<section id="contact" className="contact"><div className="container contact-box"><div><label>CONTACT</label><h2>Autosleutelprobleem? <em>Bel ons.</em></h2><p>Vertel ons kort wat er aan de hand is. Wij helpen u graag en kunnen vooraf beoordelen wat er nodig is.</p><div className="details"><a href={tel}><small>TELEFOON</small><strong>06 48 65 92 79</strong></a><a href="mailto:autosleutel.rivierenland@gmail.com"><small>E-MAIL</small><strong>autosleutel.rivierenland@gmail.com</strong></a></div><a className="review-link" href={googleReviews} target="_blank" rel="noreferrer">Bekijk onze beoordelingen op Google ↗</a></div><div className="contact-actions"><a className="btn primary large" href={tel}>Bel Autosleutel Rivierenland <b>→</b></a><a className="btn whatsapp large" href={whatsapp} target="_blank" rel="noreferrer">WhatsApp ons <b>↗</b></a><p>Ma–do 09:00–21:00 · vrijdag gesloten · za–zo 09:00–21:00</p></div></div></section>
<footer><div className="container footer-grid"><a className="logo-frame footer-logo" href="#top"><Image src="/logo.svg" alt="Autosleutel Rivierenland" width={220} height={89} unoptimized/></a><div><b>DIENSTEN</b><a href="/diensten/autosleutel-bijmaken">Autosleutel bijmaken</a><a href="/diensten/autosleutel-kwijt">Autosleutels kwijt</a><a href="/diensten/schadevrij-openen">Schadevrij openen</a><a href="/mercedes-contactslot">Mercedes contactsloten vervangen</a></div><div><b>CONTACT</b><a href="/tiel">Autosleutel Tiel</a><a href={tel}>06 48 65 92 79</a></div><div><b>BEDRIJF</b><span>Tiel · Service op locatie</span><a href="mailto:autosleutel.rivierenland@gmail.com">E-mail</a></div></div><div className="container footer-bottom"><span>© 2026 Autosleutel Rivierenland</span><span>KvK 94298033</span><span>BTW-plichtig</span></div></footer><a className="float-wa" href={whatsapp} target="_blank" rel="noreferrer" aria-label="WhatsApp Autosleutel Rivierenland">WA</a></main>}
