import type { Metadata } from "next";
import Link from "next/link";

type Service = { slug:string; title:string; intro:string; label:string; text:string[]; points:string[] };
const tel="tel:+31648659279";
const whatsapp="https://wa.me/31648659279?text=Hallo%20Autosleutel%20Rivierenland%2C%20ik%20heb%20hulp%20nodig%20met%20mijn%20autosleutel.";

const services: Service[]=[
 {slug:"autosleutel-bijmaken",label:"AUTOSLEUTEL BIJMAKEN",title:"Autosleutel bijmaken",intro:"Een extra autosleutel laten maken in Tiel of op locatie? Wij helpen u met een passende sleutel voor uw voertuig.",text:["Een reservesleutel voorkomt veel gedoe wanneer uw enige werkende autosleutel verloren raakt of defect raakt. Voor geschikte voertuigen kunnen wij een extra autosleutel leveren, passend maken en waar nodig aanmelden bij het voertuig.","De mogelijkheden verschillen per merk, model, bouwjaar en uitvoering. Stuur ons daarom vooraf de voertuiggegevens. Dan kunnen wij gericht aangeven wat er nodig is en of wij de sleutel kunnen verzorgen."],points:["Extra autosleutel voor geschikte voertuigen","Met of zonder afstandsbediening, afhankelijk van het voertuig","Vooraf beoordeling op merk, model en uitvoering"]},
 {slug:"autosleutel-kwijt",label:"AUTOSLEUTELS KWIJT",title:"Autosleutels kwijt",intro:"Uw autosleutels kwijt en geen werkende reservesleutel meer? Wij beoordelen wat er voor uw auto mogelijk is.",text:["Een autosleutel verliezen is vervelend, zeker wanneer er geen reservesleutel meer beschikbaar is. Voor veel voertuigen kan een nieuwe sleutel een oplossing zijn. Wij bekijken eerst de situatie en de mogelijkheden voor uw specifieke auto.","Neem bij contact het merk, model en bouwjaar mee en vertel of u nog een sleutel, sleutelblad of afstandsbediening heeft. Zo kunnen wij sneller beoordelen welke vervolgstap nodig is."],points:["Nieuwe sleutel bij verlies voor geschikte voertuigen","Beoordeling van de beschikbare oplossing","Service op locatie in Tiel en de regio"]},
 {slug:"behuizingen-vervangen",label:"SLEUTELBEHUIZING",title:"Behuizing van autosleutel vervangen",intro:"Is de behuizing van uw autosleutel gebroken, versleten of beschadigd? Wij kunnen voor geschikte sleutels de behuizing vervangen.",text:["Een autosleutel kan technisch nog goed werken terwijl de behuizing versleten of gebroken is. Een nieuwe behuizing kan dan een praktische oplossing zijn en voorkomt dat knoppen, printplaat of sleutelblad verder beschadigen.","Wij beoordelen de bestaande sleutel en controleren welke behuizing daarbij past. Het doel is dat uw bestaande sleutel weer netjes en stevig gebruikt kan worden."],points:["Vervangen van beschadigde sleutelbehuizingen","Knoppen en bestaande sleutelonderdelen beoordelen","Geschiktheid vooraf controleren"]},
 {slug:"schadevrij-openen",label:"SCHADEVRIJ OPENEN",title:"Auto schadevrij openen",intro:"Buitengesloten van uw auto? Wij proberen het voertuig zo zorgvuldig mogelijk te openen zonder onnodige schade.",text:["Een auto forceren kan schade veroorzaken aan slot, deur, rubbers of carrosserie. Daarom bekijken wij eerst het voertuig en de situatie en kiezen we een passende manier om toegang te krijgen.","De mogelijkheden hangen af van het merk, model en de uitvoering. Geef bij contact uw locatie en voertuiggegevens door, zodat wij kunnen inschatten wat mogelijk is."],points:["Zorgvuldig openen van afgesloten voertuigen","Zo min mogelijk risico op schade","Mobiele service in Tiel en omgeving"]},
 {slug:"diagnose-uitlezen",label:"DIAGNOSE & UITLEZEN",title:"Diagnose en uitlezen",intro:"Een auto die niet start of een sleutel niet herkent, vraagt om een gerichte diagnose voordat onderdelen worden vervangen.",text:["Een startprobleem kan meerdere oorzaken hebben. Een sleutel, voertuigmodule of ander onderdeel kan verantwoordelijk zijn. Door de auto uit te lezen en de klacht gericht te beoordelen, ontstaat een duidelijker beeld van het probleem.","Wij bespreken daarna wat de mogelijke vervolgstap is. Niet iedere storing kan op locatie worden opgelost; daar zijn we vooraf duidelijk over."],points:["Uitlezen van voertuigsystemen","Onderzoeken van sleutel- en startproblemen","Gericht bepalen van de vervolgstap"]}
];

export function generateStaticParams(){return services.map(s=>({slug:s.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const s=services.find(x=>x.slug===slug);return{title:s?`${s.title} | Autosleutel Rivierenland`:"Autosleutelservice Tiel",description:s?.intro??"Autosleutelservice vanuit Tiel."};}

export default async function ServicePage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const service=services.find(s=>s.slug===slug)??services[0];
 return <main>
  <header className="header"><div className="container nav-inner"><Link className="logo-frame" href="/"><img src="/logo.svg" alt="Autosleutel Rivierenland" width={220} height={89}/></Link><nav aria-label="Hoofdnavigatie"><Link href="/">Home</Link><Link href="/#diensten">Diensten</Link><Link href="/mercedes-contactslot">Mercedes contactslot vervangen</Link><Link href="/#zakelijk">Zakelijk</Link><Link href="/#contact">Contact</Link></nav><a className="nav-phone" href={tel}><span>06 48 65 92 79</span></a></div></header>
  <section className="premium-hero"><div className="container hero-inner"><div className="hero-copy"><div className="eyebrow"><i/> Autosleutel Rivierenland · Tiel</div><h1>{service.title}</h1><p className="hero-text">{service.intro}</p><div className="actions"><a className="btn primary" href={tel}>Bel direct <b>→</b></a><a className="btn hero-secondary" href={whatsapp} target="_blank" rel="noreferrer">WhatsApp <b>↗</b></a></div><div className="hero-trust"><span>✓ Service op locatie</span><span>✓ 1 jaar garantie</span><span>✓ Tiel en regio</span></div></div><div className="hero-image-wrap"/></div></section>
  <section className="section service-detail-section"><div className="container"><div className="detail-intro"><label>{service.label}</label><h2>Goede service begint met <em>duidelijkheid.</em></h2><p>{service.text[0]}</p></div><div className="detail-grid"><article><span>01</span><h3>Wat wij voor u doen</h3><p>{service.text[1]}</p></article><article><span>02</span><h3>Belangrijk om te weten</h3><p>{service.points.join(" · ")}</p></article><article><span>03</span><h3>Vooraf controleren</h3><p>De mogelijkheden verschillen per voertuig. Stuur daarom merk, model, bouwjaar en eventueel kenteken mee. Wij beoordelen vooraf wat voor uw auto mogelijk is.</p></article></div></div></section>
  <section className="section capability"><div className="container capability-grid"><div><label>VANUIT TIEL</label><h2>Service op locatie in <em>de regio.</em></h2></div><div><p>Autosleutel Rivierenland helpt particulieren, garages en autobedrijven vanuit Tiel. Voor werkzaamheden in Tiel kunt u ook op afspraak langskomen.</p><Link className="text-link" href="/tiel">Autosleutelservice in Tiel →</Link></div></div></section>
  <section className="contact"><div className="container contact-box"><div><label>CONTACT</label><h2>Hulp nodig met uw <em>autosleutel?</em></h2><p>Stuur uw voertuiggegevens of bel ons direct. Wij helpen u graag.</p></div><div className="contact-actions"><a className="btn primary large" href={tel}>Bel 06 48 65 92 79 <b>→</b></a><a className="btn whatsapp large" href={whatsapp} target="_blank" rel="noreferrer">WhatsApp ons <b>↗</b></a></div></div></section>
  <footer><div className="container footer-grid"><Link className="logo-frame footer-logo" href="/"><img src="/logo.svg" alt="Autosleutel Rivierenland" width={220} height={89}/></Link><div><b>DIENSTEN</b>{services.slice(0,4).map(s=><Link key={s.slug} href={`/diensten/${s.slug}`}>{s.title}</Link>)}</div><div><b>CONTACT</b><Link href="/mercedes-contactslot">Mercedes contactslot vervangen</Link><Link href="/tiel">Autosleutel Tiel</Link></div><div><b>CONTACT</b><a href={tel}>06 48 65 92 79</a><a href="mailto:autosleutel.rivierenland@gmail.com">E-mail</a></div></div></footer>
 </main>;
}
