import type { Metadata } from "next";
import Link from "next/link";
import "./service-pages.css";

type Service = { slug:string; title:string; label:string; intro:string; seoTitle:string; text:string[]; points:string[]; steps:string[]; faqs:[string,string][]; image:string; imageAlt:string };
const tel="tel:+31648659279";
const whatsapp="https://wa.me/31648659279?text=Hallo%20Autosleutel%20Rivierenland%2C%20ik%20heb%20hulp%20nodig%20met%20mijn%20autosleutel.";
const services: Service[]=[
 {slug:"autosleutel-bijmaken",label:"AUTOSLEUTEL BIJMAKEN",title:"Een extra autosleutel.",seoTitle:"Autosleutel bijmaken in Tiel en Rivierenland",intro:"Een extra autosleutel laten maken? Wij maken voor geschikte voertuigen autosleutels met én zonder afstandsbediening, op locatie of op afspraak.",text:["Een extra autosleutel is een slimme reserve voor later. Wij kunnen voor geschikte auto's een traditionele sleutel zonder afstandsbediening, een sleutel met afstandsbediening of een moderne smartkey verzorgen. Welke sleutel nodig is, hangt af van merk, model, bouwjaar en uitvoering.","Na beoordeling maken we de sleutel passend voor uw voertuig. Waar nodig wordt de sleutel geprogrammeerd of ingeleerd en testen we de functies voordat u ermee verdergaat. Dat kan op locatie in Tiel en de regio of op afspraak.","Wij helpen zowel particuliere klanten als garages en autobedrijven. Vooraf bespreken we wat u nodig heeft, zodat u weet wat er mogelijk is voordat we aan de slag gaan."],points:["Autosleutel met of zonder afstandsbediening","Extra sleutel en reservesleutel","Sleutels programmeren en inleren voor geschikte voertuigen","Mobiele service in Tiel en Rivierenland","Ook op afspraak in Tiel"],steps:["Vertel ons merk, model en bouwjaar en welke sleutel u nu heeft.","Wij beoordelen welke sleutel en werkzaamheden voor uw auto nodig zijn.","De sleutel wordt gemaakt, geprogrammeerd en getest."],faqs:[["Kan ik een autosleutel zonder afstandsbediening laten maken?","Ja, voor geschikte voertuigen kunnen wij ook een eenvoudige sleutel zonder afstandsbediening verzorgen."],["Kan een nieuwe sleutel op locatie worden ingeleerd?","Bij geschikte voertuigen kunnen veel werkzaamheden op locatie worden uitgevoerd."],["Maken jullie ook smartkeys?","Voor geschikte voertuigen kunnen wij ook moderne smartkeys en keyless-sleutels verzorgen."],["Wat moet ik doorgeven voor een prijsindicatie?","Merk, model, bouwjaar en bij voorkeur kenteken of voertuiggegevens helpen om vooraf de mogelijkheden te beoordelen."]],image:"https://images.pexels.com/photos/10566895/pexels-photo-10566895.jpeg?auto=compress&cs=tinysrgb&w=1800",imageAlt:"Autosleutels en autosleutelservice"},
 {slug:"autosleutel-kwijt",label:"AUTOSLEUTELS KWIJT",title:"Autosleutels kwijt?",seoTitle:"Autosleutel kwijt in Tiel? Nieuwe autosleutel laten maken",intro:"Geen autosleutel meer en geen werkende reservesleutel? Wij bekijken welke oplossing voor uw auto mogelijk is en kunnen voor geschikte voertuigen een nieuwe sleutel verzorgen.",text:["Een autosleutel kwijt is vervelend, zeker als er geen reservesleutel meer beschikbaar is. Wij beginnen daarom niet met zomaar een sleutel maken, maar bekijken eerst het voertuig, de beschikbare gegevens en de situatie.","Voor geschikte voertuigen kunnen wij een nieuwe autosleutel verzorgen en waar nodig programmeren of inleren. Ook als u alleen nog een beschadigde sleutel, sleutelblad of afstandsbediening heeft, is het verstandig om dat vooraf te melden.","Wij werken mobiel in Tiel en de regio. Bij sommige werkzaamheden is een afspraak in Tiel praktischer; dat bespreken we vooraf."],points:["Nieuwe autosleutel bij verlies","Ook wanneer geen reservesleutel beschikbaar is","Beoordeling per merk, model en bouwjaar","Mobiele service in Tiel en omgeving","Voor particulieren, garages en autobedrijven"],steps:["Geef door wat u kwijt bent en welk voertuig u heeft.","Wij beoordelen de auto en bepalen welke sleutel en programmering nodig zijn.","De nieuwe sleutel wordt gemaakt, ingeleerd en getest."],faqs:[["Kunnen jullie helpen als alle autosleutels kwijt zijn?","Voor geschikte voertuigen kunnen wij onderzoeken welke mogelijkheden er zijn. De exacte oplossing verschilt per voertuig."],["Kan dit op locatie?","Veel werkzaamheden kunnen mobiel worden uitgevoerd. Soms is een afspraak in Tiel praktischer."],["Wat moet ik meenemen?","Voertuiggegevens en legitimatie zijn afhankelijk van de situatie belangrijk. We bespreken vooraf wat nodig is."],["Kunnen jullie ook een sleutel met afstandsbediening maken?","Ja, voor geschikte voertuigen kunnen wij sleutels met afstandsbediening verzorgen."]],image:"https://images.pexels.com/photos/6097/pexels-photo-6097.jpeg?auto=compress&cs=tinysrgb&w=1800",imageAlt:"Autosleutel in de hand bij een auto"},
 {slug:"behuizingen-vervangen",label:"SLEUTELBEHUIZING",title:"Een nieuwe sleutelbehuizing.",seoTitle:"Autosleutel behuizing vervangen in Tiel",intro:"Is de behuizing van uw autosleutel gebroken, versleten of beschadigd? Voor geschikte sleutels kunnen wij de behuizing vervangen en de bestaande onderdelen overzetten.",text:["Een autosleutel hoeft niet volledig vervangen te worden wanneer vooral de behuizing versleten is. Gebroken knoppen, een beschadigde kunststof behuizing of een loszittend sleutelblad kunnen het dagelijks gebruik onnodig lastig maken.","Wij beoordelen de bestaande sleutel en kijken welke behuizing daarbij past. Waar mogelijk worden de bestaande elektronische onderdelen overgezet. Daarna controleren we of de knoppen, sleutel en afstandsbediening correct functioneren.","Deze service is vooral interessant wanneer de techniek van de sleutel nog goed werkt, maar de buitenkant duidelijk versleten of beschadigd is."],points:["Behuizing van autosleutel vervangen","Bestaande onderdelen beoordelen en overzetten","Knoppen en sleutelblad controleren","Voor geschikte sleutelmodellen","Op afspraak of mobiel wanneer praktisch"],steps:["We bekijken de bestaande sleutel en de beschadiging.","We controleren welke behuizing passend is.","De onderdelen worden overgezet en de sleutel wordt getest."],faqs:[["Moet ik een compleet nieuwe autosleutel kopen?","Niet altijd. Als de elektronica nog goed is, kan een nieuwe behuizing een praktische oplossing zijn."],["Blijven de afstandsbedieningsfuncties werken?","Als de bestaande elektronica goed is en geschikt kan worden overgezet, blijven de functies behouden."],["Kunnen jullie ook de sleutelknoppen vervangen?","Dat hangt af van het type sleutel en de beschikbare behuizing of onderdelen."],["Kan ik de sleutel opsturen?","Voor deze lokale service werken we bij voorkeur op afspraak of op locatie in de regio."]],image:"https://images.pexels.com/photos/8033684/pexels-photo-8033684.jpeg?auto=compress&cs=tinysrgb&w=1800",imageAlt:"Autosleutel van dichtbij"},
 {slug:"schadevrij-openen",label:"SCHADEVRIJ OPENEN",title:"Buitengesloten van uw auto?",seoTitle:"Auto schadevrij openen in Tiel en Rivierenland",intro:"Uw autosleutel ligt in de auto of u bent buitengesloten? Wij helpen u om het voertuig zo zorgvuldig mogelijk te openen en onnodige schade te voorkomen.",text:["Een afgesloten auto openen vraagt om een passende aanpak. Forceren kan schade veroorzaken aan slot, deur, rubbers of carrosserie. Daarom beoordelen wij eerst het voertuig en de situatie voordat we een methode kiezen.","Onze mobiele service is gericht op zorgvuldig openen met zo min mogelijk risico op schade. De mogelijkheden verschillen per merk, model en uitvoering.","Geef bij contact uw locatie en voertuiggegevens door. Dan kunnen wij beter inschatten wat er nodig is en of we u op locatie kunnen helpen."],points:["Schadevrij of zo schadevrij mogelijk openen","Mobiele service in Tiel en de regio","Vooraf beoordeling van voertuig en situatie","Geschikt voor veel personenauto's","Zorgvuldige aanpak zonder onnodige schade"],steps:["U geeft uw locatie en voertuiggegevens door.","Wij beoordelen de situatie en kiezen een passende openingsmethode.","Na opening controleren we de situatie en bespreken we het vervolg."],faqs:[["Kunnen jullie elke auto schadevrij openen?","Nee. De mogelijkheden verschillen per voertuig. We beoordelen vooraf wat verantwoord is."],["Komen jullie naar mijn locatie?","Ja, deze service is juist gericht op mobiele hulp in Tiel en de regio."],["Wat moet ik doorgeven?","Uw locatie, merk, model en bouwjaar zijn nuttig om de situatie vooraf te beoordelen."],["Wat als de sleutel in de auto ligt?","Dat is een veelvoorkomende situatie. We bekijken welke veilige openingsmethode bij het voertuig past."]],image:"https://images.pexels.com/photos/17124737/pexels-photo-17124737.jpeg?auto=compress&cs=tinysrgb&w=1800",imageAlt:"Professioneel gereedschap bij een autoslot"},
 {slug:"diagnose-uitlezen",label:"DIAGNOSE & UITLEZEN",title:"Auto uitlezen. Storing vinden.",seoTitle:"Auto uitlezen en diagnose stellen in Tiel",intro:"Een foutmelding, waarschuwingslampje of auto die niet goed start? Voor geschikte voertuigen kunnen wij de auto uitlezen, foutcodes controleren en helpen de oorzaak van een storing te bepalen.",text:["Een foutmelding vertelt niet altijd direct wat er defect is. Daarom kijken we naar de klacht, lezen we beschikbare voertuigsystemen uit en beoordelen we de aanwezige foutcodes. Zo ontstaat een beter beeld van de storing voordat er onderdelen worden vervangen.","Deze service kan interessant zijn bij elektronische storingen, startproblemen, sleutelherkenning en andere klachten waarbij een diagnose nodig is. We zijn duidelijk over wat we wel en niet kunnen vaststellen.","Niet iedere diagnose leidt direct tot een reparatie. Soms is vervolgonderzoek of een gespecialiseerde werkplaats nodig. Ook daar zijn we vooraf eerlijk over."],points:["Auto uitlezen en foutcodes controleren","Foutmeldingen en storingen onderzoeken","Diagnose stellen bij start- en sleutelproblemen","Elektronische voertuigsystemen beoordelen","Vervolgstap bepalen op basis van de diagnose"],steps:["U beschrijft de klacht en eventuele foutmelding.","Wij lezen de beschikbare voertuiggegevens en foutcodes uit.","We bespreken wat de diagnose betekent en welke vervolgstap logisch is."],faqs:[["Kunnen jullie elke foutmelding oplossen?","Nee. Uitlezen en diagnose stellen is niet hetzelfde als iedere reparatie uitvoeren. We geven vooraf aan wat we kunnen beoordelen."],["Kunnen jullie een auto op locatie uitlezen?","Voor geschikte voertuigen kan diagnose en uitlezen mobiel worden uitgevoerd."],["Kunnen jullie foutcodes wissen?","Dat kan in sommige situaties, maar eerst moet duidelijk zijn waarom de foutcode aanwezig is. Alleen wissen zonder oorzaak te onderzoeken is meestal geen goede oplossing."],["Doen jullie ook sleutel- en startdiagnose?","Ja, voor geschikte voertuigen kunnen we sleutelherkenning en startproblemen meenemen in de diagnose."]],image:"https://images.pexels.com/photos/4116193/pexels-photo-4116193.jpeg?auto=compress&cs=tinysrgb&w=1800",imageAlt:"Auto uitlezen met professionele diagnoseapparatuur"}
];

export function generateStaticParams(){return services.map(s=>({slug:s.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const s=services.find(x=>x.slug===slug);return{title:s?s.seoTitle+" | Autosleutel Rivierenland":"Autosleutelservice Tiel",description:s?.intro??"Autosleutelservice vanuit Tiel."};}

export default async function ServicePage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const service=services.find(s=>s.slug===slug)??services[0];
 return <main className="service-page">
  <header className="header"><div className="container nav-inner"><Link className="logo-frame" href="/"><img src="/logo.svg" alt="Autosleutel Rivierenland" width={220} height={89}/></Link><nav aria-label="Hoofdnavigatie"><Link href="/">Home</Link><Link href="/#diensten">Diensten</Link><Link href="/mercedes-contactslot">Mercedes contactslot vervangen</Link><Link href="/#zakelijk">Zakelijk</Link><Link href="/#contact">Contact</Link></nav><a className="nav-phone" href={tel}><span>06 48 65 92 79</span></a></div></header>
  <div className="service-breadcrumb container"><Link href="/">Home</Link><span>›</span><Link href="/#diensten">Diensten</Link><span>›</span><b>{service.title}</b></div>
  <section className="service-hero"><div className="container service-hero-grid"><div className="service-hero-copy"><div className="service-eyebrow">{service.label}</div><h1>{service.title}</h1><p>{service.intro}</p><div className="service-trust"><span>✓ Mobiele service</span><span>✓ Tiel en regio</span><span>✓ 1 jaar garantie op autosleutels</span></div></div><div className="service-photo" style={{backgroundImage:`url("${service.image}")`}} role="img" aria-label={service.imageAlt}><div className="photo-badge">Autosleutel Rivierenland<br/><small>Professionele service</small></div></div></div></section>
  <section className="section service-offer"><div className="container offer-grid"><div className="offer-photo" style={{backgroundImage:`url("${service.image}")`}} role="img" aria-label={service.imageAlt}></div><div className="offer-copy"><label>WAT WIJ BIEDEN</label><h2>{service.seoTitle.split(" in ")[0]}, <em>zonder gedoe.</em></h2><p>{service.text[0]}</p><p>{service.text[1]}</p><div className="check-grid">{service.points.map(point=><span key={point}>✓ {point}</span>)}</div></div></div></section>
  <section className="section service-steps"><div className="container"><div className="steps-head"><div><label>HOE HET WERKT</label><h2>Van eerste contact tot <em>oplossing.</em></h2></div><p>We beginnen met de situatie en voertuiggegevens. Daarna bespreken we wat er nodig is en voeren we de werkzaamheden uit wanneer de situatie daarvoor geschikt is.</p></div><div className="steps-grid">{service.steps.map((step,i)=><article key={step}><span>0{i+1}</span><h3>{["Situatie bespreken","Voertuig beoordelen","Werkzaamheden uitvoeren"][i]}</h3><p>{step}</p></article>)}</div></div></section>
  <section className="section service-info"><div className="container info-grid"><div><label>VANUIT TIEL</label><h2>Mobiel waar het kan. <em>Op afspraak waar het beter past.</em></h2></div><div><p>{service.text[2]}</p><p>Autosleutel Rivierenland helpt particulieren, garages en autobedrijven in Tiel en de omliggende regio. Voor geschikte werkzaamheden kunt u ook op afspraak langskomen.</p><Link href="/tiel" className="service-link">Meer over autosleutelservice in Tiel →</Link></div></div></section>
  <section className="section service-faq"><div className="container faq-grid"><div><label>VEELGESTELDE VRAGEN</label><h2>Snel antwoord op uw <em>vragen.</em></h2></div><div className="faq-list">{service.faqs.map(([q,a])=><details key={q}><summary>{q}<span>⌄</span></summary><p>{a}</p></details>)}</div></div></section>
  <section className="service-cta"><div className="container service-cta-grid"><div><label>HULP NODIG?</label><h2>{service.title} <em>nodig?</em></h2><p>Vertel ons wat er aan de hand is. We bespreken eerst de mogelijkheden voor uw voertuig.</p></div><div className="cta-actions"><a className="btn cta-primary" href={tel}>Bel direct <b>06 48 65 92 79</b><span>→</span></a><a className="btn cta-secondary" href={whatsapp} target="_blank" rel="noreferrer">WhatsApp <b>Stuur een bericht</b><span>↗</span></a><small>Ma–do 09:00–21:00 · vrijdag gesloten · za–zo 09:00–21:00</small></div></div></section>
  <footer><div className="container footer-grid"><Link className="logo-frame footer-logo" href="/"><img src="/logo.svg" alt="Autosleutel Rivierenland" width={220} height={89}/></Link><div><b>DIENSTEN</b>{services.slice(0,4).map(s=><Link key={s.slug} href={`/diensten/${s.slug}`}>{s.title}</Link>)}</div><div><b>REGIO</b><Link href="/tiel">Autosleutel Tiel</Link><Link href="/mercedes-contactslot">Mercedes contactslot vervangen</Link></div><div><b>CONTACT</b><a href={tel}>06 48 65 92 79</a><a href="mailto:autosleutel.rivierenland@gmail.com">E-mail</a><span>Tiel · Rivierenland</span></div></div></footer>
 </main>;
}
