import type { Metadata } from "next";
import Image from "next/image";
import "./tiel.css";

export const metadata: Metadata = {
  title: "Autosleutel Tiel | Autosleutel Rivierenland",
  description: "Autosleutelservice in Tiel vanuit Autosleutel Rivierenland. Autosleutel bijmaken, autosleutels kwijt, schadevrij openen en andere sleutelproblemen.",
  alternates: { canonical: "/tiel" },
  openGraph: { title: "Autosleutel Tiel | Autosleutel Rivierenland", description: "Professionele autosleutelservice vanuit Tiel, voor Tiel en de regio.", url: "https://autosleutelrivierenland.nl/tiel", siteName: "Autosleutel Rivierenland", locale: "nl_NL", type: "website" },
};

const tel = "tel:+31648659279";
const whatsapp = "https://wa.me/31648659279?text=Hallo%20Autosleutel%20Rivierenland%2C%20ik%20heb%20hulp%20nodig%20in%20Tiel%20met%20mijn%20autosleutel.";
const services = [
  ["01", "Autosleutel bijmaken", "Een extra sleutel nodig? Voor geschikte voertuigen maken en programmeren wij een passende sleutel.", "/diensten/autosleutel-bijmaken"],
  ["02", "Autosleutels kwijt", "Geen werkende sleutel meer? Wij beoordelen de situatie en bespreken welke oplossing mogelijk is.", "/diensten/autosleutel-kwijt"],
  ["03", "Schadevrij openen", "Buitengesloten in Tiel? Wij openen uw auto zo zorgvuldig mogelijk en proberen schade te voorkomen.", "/diensten/schadevrij-openen"],
  ["04", "Mercedes contactslot vervangen", "Voor geschikte Mercedes-modellen met FBS3 kunnen wij het contactslot beoordelen en vervangen.", "/mercedes-contactslot"],
];
const places = ["Culemborg", "Geldermalsen", "Buren", "Zaltbommel", "Leerdam", "Gorinchem"];
const structuredData = { "@context": "https://schema.org", "@type": "WebPage", name: "Autosleutel Tiel", url: "https://autosleutelrivierenland.nl/tiel", description: "Lokale autosleutelservice vanuit Tiel van Autosleutel Rivierenland.", about: { "@type": "Locksmith", name: "Autosleutel Rivierenland", telephone: "+31648659279", address: { "@type": "PostalAddress", addressLocality: "Tiel", addressRegion: "Gelderland", addressCountry: "NL" } } };
function PhoneIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.6 2.8 9.4 2l2.1 5.1-2.4 1.8c1.2 2.5 3.1 4.5 5.7 5.7l1.8-2.4 5.1 2.1-.8 2.8c-.4 1.5-1.8 2.5-3.4 2.4C10.2 18.8 5.2 13.8 4.5 7.7c-.2-1.6.7-3.1 2.1-3.7Z" fill="currentColor"/></svg>}
function WhatsAppIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2.5a9.4 9.4 0 0 0-8.1 14.2L2.7 21.4l4.9-1.2A9.4 9.4 0 1 0 12 2.5Zm0 16.9a7.5 7.5 0 0 1-3.8-1l-.3-.2-2.9.7.8-2.8-.2-.3a7.5 7.5 0 1 1 6.4 3.6Zm4.1-5.6c-.2-.1-1.4-.7-1.6-.8-.2-.1-.4-.1-.5.1-.2.2-.6.8-.7 1-.1.2-.3.2-.5.1-1.5-.8-2.5-1.5-3.5-3.1-.3-.5.3-.5.8-1.5.1-.2 0-.4 0-.5l-.7-1.6c-.2-.4-.4-.4-.5-.4h-.4c-.2 0-.5.1-.7.3-.2.2-.9.9-.9 2.2s.9 2.6 1 2.8c.1.2 1.8 2.9 4.4 4 .6.3 1.1.4 1.5.5.6.2 1.2.1 1.7.1.5-.1 1.4-.6 1.6-1.2.2-.6.2-1.1.1-1.2-.1 0-.3-.1-.6-.2Z" fill="currentColor"/></svg>}
function Header(){return <header className="header"><div className="container nav-inner"><a className="logo-frame" href="/" aria-label="Autosleutel Rivierenland home"><Image src="/logo.svg" alt="Autosleutel Rivierenland" width={220} height={89} priority unoptimized/></a><nav aria-label="Hoofdnavigatie"><a href="/">Home</a><a href="/#diensten">Diensten</a><a href="/mercedes-contactslot">Mercedes contactslot vervangen</a><a href="/#zakelijk">Zakelijk</a><a href="/#contact">Contact</a></nav><a className="nav-phone" href={tel}><b>☎</b><span>06 48 65 92 79</span></a></div></header>}

export default function TielPage(){return <main className="tiel-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData)}}/><Header/>
<section className="tiel-hero"><div className="container tiel-hero-grid"><div className="tiel-hero-copy"><div className="tiel-eyebrow">AUTOSLEUTELSERVICE UIT TIEL</div><h1>Autosleutel <span>Tiel.</span></h1><p>Autosleutel Rivierenland is gevestigd in Tiel. Vanuit hier helpen wij particulieren, garages en autobedrijven met autosleutels, sleutelproblemen en schadevrij openen.</p><p>Voor veel werkzaamheden is mobiele service mogelijk. In Tiel kunt u voor geschikte werkzaamheden ook op afspraak langskomen.</p></div><div className="tiel-hero-visual"><div className="visual-grid"></div><div className="visual-key"><span></span><i></i><i></i></div><div className="visual-caption"><small>ONZE BASIS</small><strong>TIEL</strong><span>Rivierenland · Gelderland</span></div></div></div></section>
<section className="section tiel-intro"><div className="container two-col"><div><label>WAAROM TIEL?</label><h2>Een lokale autosleutelservice, <em>dichtbij.</em></h2></div><div><p>Tiel is de thuisbasis van Autosleutel Rivierenland. Wanneer er iets misgaat met uw autosleutel wilt u vooral weten waar u terechtkunt. Vanuit Tiel kunnen wij snel schakelen voor klanten in de stad en de omliggende regio.</p><p>We bespreken vooraf wat er aan de hand is en welke gegevens van de auto nodig zijn. Zo kunnen we beter inschatten welke sleutel, programmering of andere werkzaamheden nodig zijn.</p></div></div></section>
<section className="section tiel-services"><div className="container"><div className="section-head"><div><label>AUTOSLEUTEL IN TIEL</label><h2>Waarvoor kunt u bij ons <em>terecht?</em></h2></div><p>De mogelijkheden verschillen per merk, model, bouwjaar en uitvoering. Daarom beoordelen wij de situatie vooraf.</p></div><div className="tiel-service-grid">{services.map(([n,title,text,href])=><a className="tiel-service" href={href} key={n}><span className="service-no">{n}</span><div className="service-line"></div><h3>{title}</h3><p>{text}</p><b>Meer informatie <span>→</span></b></a>)}</div></div></section>
<section className="tiel-region section"><div className="container region-box"><div className="region-copy"><label>IN DE REGIO</label><h2>Dichtbij voor Tiel. <em>Actief in Rivierenland.</em></h2><p>Vanuit Tiel helpen wij klanten in de omliggende regio. Onder andere in Culemborg, Geldermalsen, Buren, Zaltbommel, Leerdam en Gorinchem.</p><div className="place-list">{places.map(place=><span key={place}>{place}</span>)}</div><div className="region-note"><b>Mobiele service</b><span>Veel werkzaamheden kunnen op locatie worden uitgevoerd.</span></div></div><div className="region-visual" aria-label="Schematische weergave van de regio rond Tiel"><div className="region-lines"></div><div className="tiel-node"><span></span><b>Tiel</b><small>vertrekpunt</small></div>{places.map((place,i)=><div className={`place-node node-${i+1}`} key={place}><i></i><span>{place}</span></div>)}<div className="region-route"><span></span><span></span><span></span></div></div></div></section>
<section className="section tiel-info"><div className="container info-box"><div><label>DIAGNOSE & UITLEZEN</label><h2>Foutmeldingen <em>in beeld.</em></h2></div><div><p>Heeft uw auto een foutmelding, brandend waarschuwingslampje of een storing die u niet kunt plaatsen? Voor geschikte voertuigen kunnen wij de auto uitlezen en foutcodes controleren.</p><p>Op basis van de beschikbare gegevens kunnen we beoordelen waar een storing vandaan kan komen en welke vervolgstap logisch is. Zo combineren we autosleutelservice met <strong>auto uitlezen, foutmeldingen vinden en diagnose stellen.</strong></p><p><strong>Niet beschikbaar:</strong> BMW, Renault en Volvo. Bij twijfel kunt u vooraf het merk, model en bouwjaar doorgeven.</p></div></div></section>
<section className="tiel-cta"><div className="container tiel-cta-box"><div><label>HULP NODIG IN TIEL?</label><h2>Vertel ons wat er met uw <em>autosleutel</em> aan de hand is.</h2><p>We bespreken eerst uw situatie. Daarna weet u welke mogelijkheden er zijn.</p></div><div className="tiel-cta-actions"><a className="btn primary" href={tel}><span className="btn-icon"><PhoneIcon/></span><span>Bel direct</span><b>06 48 65 92 79</b></a><a className="btn hero-secondary" href={whatsapp} target="_blank" rel="noreferrer"><span className="btn-icon whatsapp-icon"><WhatsAppIcon/></span><span>WhatsApp</span><b>Stuur een bericht →</b></a><small>Ma–do 09:00–21:00 · vrijdag gesloten · za–zo 09:00–21:00</small></div></div></section>
<footer><div className="container footer-grid"><a className="logo-frame footer-logo" href="/"><Image src="/logo.svg" alt="Autosleutel Rivierenland" width={220} height={89} unoptimized/></a><div><b>DIENSTEN</b><a href="/diensten/autosleutel-bijmaken">Autosleutel bijmaken</a><a href="/diensten/autosleutel-kwijt">Autosleutels kwijt</a><a href="/diensten/schadevrij-openen">Schadevrij openen</a><a href="/mercedes-contactslot">Mercedes contactsloten vervangen</a></div><div><b>REGIO</b><a href="/tiel">Autosleutel Tiel</a><span>Tiel · Rivierenland</span><a href="mailto:autosleutel.rivierenland@gmail.com">E-mail</a></div><div><b>CONTACT</b><a href={tel}>06 48 65 92 79</a><span>Service op locatie</span></div></div><div className="container footer-bottom"><span>© 2026 Autosleutel Rivierenland</span><span>KvK 94298033</span><span>BTW-plichtig</span></div></footer>
</main>}
